generatorApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect
from django.urls import path, reverse
from .views import *

app_name = "generatorApp"
urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),

    # accounts
    path('accounts/login/', views.LoginUserView.as_view(), name='login'),
    path('accounts/register/', views.RegisterUserView.as_view(), name='register'),
    path('accounts/logout/', views.LogoutUserView.as_view(), name='logout'),

    # docs
    path('docs/', lambda request: HttpResponseRedirect(reverse('generatorApp:docs', kwargs={'lang': 'eng', 'file': 'intro'})), name='redirect-docs'),
    path('docs/<str:lang>/<str:file>/', views.DocsView.as_view(), name='docs'),

    # schedules
    path('schedules/', views.SchedulesListView.as_view(), name='schedules_base'),
    path('schedules/<str:username>/', views.SchedulesListView.as_view(), name='schedules'),
    path('schedules/<str:username>/<str:schedule_name>/', views.ScheduleView.as_view(), name='schedule'),
    path('schedules/<str:username>/<str:schedule_name>/generate/', views.GenerateScheduleView.as_view(), name='generate_schedule'),

    # settings
    path('schedules/<str:username>/<str:schedule_name>/export_settings/', views.ExportScheduleView.as_view(), name='export_schedule'),
    path('schedules/<str:username>/<str:schedule_name>/settings/', views.ScheduleSettingsView.as_view(), name='settings'),

    # forms to add data
    path('schedules/<str:username>/<str:schedule_name>/lesson_hours/', views.LessonHoursView.as_view(), name='lesson_hours'),
    path('schedules/<str:username>/<str:schedule_name>/classroom_types/', views.ClassroomTypesView.as_view(), name='classroom_types'),
    path('schedules/<str:username>/<str:schedule_name>/classrooms/', views.ClassroomsView.as_view(), name='classroom'),
    path('schedules/<str:username>/<str:schedule_name>/teachers/', views.TeachersView.as_view(), name='teachers'),
    path('schedules/<str:username>/<str:schedule_name>/classes/', views.ClassesView.as_view(), name='classes'),
    path('schedules/<str:username>/<str:schedule_name>/subject_names/', views.SubjectNamesView.as_view(), name='subject_names'),
    path('schedules/<str:username>/<str:schedule_name>/subjects/', views.SubjectsView.as_view(), name='subjects'),

    # delete
    path('schedules/<str:username>/<str:schedule_name>/delete/', views.DeleteScheduleView.as_view(), name='delete_schedule'),
    path('schedules/<str:username>/<str:schedule_name>/<str:model>/delete/', views.DeleteDataView.as_view(), name='delete_data'),
    path('remove-message/', views.remove_message, name='remove_message'),

    # upload data
    path('schedules/<str:username>/<str:schedule_name>/<str:model>/upload/', views.UploadDataView.as_view(), name='upload_data'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scheduleGenerator/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("generatorApp.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("admin/", admin.site.urls),
]

generatorApp/models.py
import json
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import ast


class ScheduleList(models.Model):
    user_id = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=800, default='')
    created_date = models.DateTimeField(default=timezone.now)
    content = models.TextField()

    def __str__(self):
        return self.name


class ClassroomTypes(models.Model):
    in_id = models.TextField(default=None, null=True)
    schedule_id = models.ForeignKey(ScheduleList, on_delete=models.CASCADE)
    description = models.CharField(max_length=150)

    class Meta:
        unique_together = ('schedule_id', 'in_id')

    def __str__(self):
        return self.description


class Classrooms(models.Model):
    in_id = models.TextField(default=None, null=True)
    schedule_id = models.ForeignKey(ScheduleList, on_delete=models.CASCADE)
    type_id = models.ForeignKey(ClassroomTypes, default=0, on_delete=models.SET_DEFAULT)
    name = models.CharField(max_length=30)

    class Meta:
        unique_together = ('schedule_id', 'in_id')

    def __str__(self):
        return self.name


class Teachers(models.Model):
    in_id = models.TextField(default=None, null=True)
    schedule_id = models.ForeignKey(ScheduleList, on_delete=models.CASCADE)
    main_classroom_id = models.ForeignKey(Classrooms, null=True, default=None, on_delete=models.SET_DEFAULT)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    possible_subjects = models.CharField(max_length=300)
    start_hour_index = models.CharField(max_length=30)
    end_hour_index = models.CharField(max_length=30)
    days = models.CharField(max_length=30)

    class Meta:
        unique_together = ('schedule_id', 'in_id')

    def __str__(self):
        return str(self.name) + " " + str(self.surname)


class LessonHours(models.Model):
    in_id = models.TextField(default=None, null=True)
    schedule_id = models.ForeignKey(ScheduleList, on_delete=models.CASCADE)
    start_hour = models.CharField(max_length=30)
    duration = models.IntegerField()

    class Meta:
        unique_together = ('schedule_id', 'in_id')

    def __str__(self):
        return self.start_hour


class Classes(models.Model):
    in_id = models.TextField(default=None, null=True)
    schedule_id = models.ForeignKey(ScheduleList, on_delete=models.CASCADE)
    supervising_teacher_id = models.ForeignKey(Teachers, default=None, on_delete=models.SET_DEFAULT)
    starting_lesson_hour_id = models.ForeignKey(LessonHours, default=0, on_delete=models.SET_DEFAULT)
    grade = models.IntegerField()
    class_signature = models.CharField(max_length=10)

    class Meta:
        unique_together = ('schedule_id', 'in_id')

    def __str__(self):
        return str(self.grade) + str(self.class_signature)


class SubjectNames(models.Model):
    in_id = models.TextField(default=None, null=True)
    schedule_id = models.ForeignKey(ScheduleList, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        unique_together = ('schedule_id', 'in_id')

    def __str__(self):
        return self.name


class ScheduleSettings(models.Model):
    schedule_id = models.ForeignKey(ScheduleList, on_delete=models.CASCADE)
    content = models.TextField(
        default=json.dumps({
            "min_lessons_per_day": 5,
            "max_lessons_per_day": 9,
            "days": ["monday", "tuesday", "wednesday", "thursday", "friday"]
        })
    )

    def __str__(self):
        return self.content


class Subject(models.Model):
    in_id = models.TextField(default=None, null=True)
    schedule_id = models.ForeignKey(ScheduleList, on_delete=models.CASCADE)

    classes_id = models.ForeignKey(Classes, on_delete=models.CASCADE)
    subject_name_id = models.ForeignKey(SubjectNames, on_delete=models.CASCADE)
    lesson_hour_id = models.ForeignKey(LessonHours, null=True, default=None, on_delete=models.SET_DEFAULT)
    teachers_id = models.TextField(default=None, null=True)
    classroom_id = models.ForeignKey(Classrooms, null=True, default=None, on_delete=models.SET_DEFAULT)
    subject_count_in_week = models.IntegerField()
    number_of_groups = models.IntegerField()
    max_stack = models.IntegerField()
    classroom_types = models.CharField(max_length=30)

    class Meta:
        unique_together = ('schedule_id', 'in_id')

    @staticmethod
    def check_teachers(teachers_id, schedule_id):
        for teacher_id in ast.literal_eval(teachers_id):
            try:
                Teachers.objects.get(schedule_id=schedule_id, _id=teacher_id)
            except Teachers.DoesNotExist:
                return False
        return True

generatorApp/views/general.py
import os
import markdown
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.conf import settings
from django.conf import settings
from django.http import JsonResponse, HttpResponseNotFound
from django.views.decorators.csrf import csrf_exempt
import json


def home(request):
    return render(request, 'generatorApp/home.html')


class DocsView(View):
    docs_path = os.path.join(settings.BASE_DIR, 'generatorApp/DOCS')

    def get(self, request, lang, file):
        selected_language = request.GET.get('language', lang)

        file_path = os.path.join(self.docs_path, lang, file + '.md')
        file_context = open(file_path, mode="r", encoding="utf-8").read()
        file_context = markdown.markdown(file_context)

        if lang != selected_language:
            return HttpResponseRedirect(
                reverse('generatorApp:docs', kwargs={'lang': selected_language, 'file': 'intro'}))
        return render(request, 'generatorApp/docs.html', {'lang': selected_language, 'file_content': file_context})


@csrf_exempt
def remove_message(request):
    if not settings.DEBUG:
        # Return 404 if not in DEBUG mode
        return HttpResponseNotFound("This endpoint is only available in DEBUG mode.")

    if request.method == 'POST':
        data = json.loads(request.body)
        msg_type = data.get('msg_type')
        if msg_type and msg_type in request.session:
            del request.session[msg_type]
            request.session.modified = True
        return JsonResponse({'status': 'success'})
    return JsonResponse({'status': 'error'}, status=400)

generatorApp/views/user.py
from django.shortcuts import HttpResponseRedirect, render
from ..forms import *
from django.urls import reverse, reverse_lazy
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.db.models import Q
import re


class LoginUserView(View):
    form_class = LoginForm
    template_name = 'generatorApp/login.html'
    success_url = reverse_lazy('generatorApp:home')
    next_page = reverse_lazy('generatorApp:home')

    def get(self, request):
        context = {}
        context['error_msg'] = self.request.session.pop('error_msg', '')
        return render(self.request, self.template_name)

    def post(self, request):
        context = {}
        username = self.request.POST.get('login')
        password = self.request.POST.get('password')
        remember_me = self.request.POST.get('remember-me')
        ogg = User.objects.filter(
            Q(email=username) | Q(username=username)
        ).first()

        if not ogg:
            self.request.session['error_msg'] = "Login/e-mail doesn't exist"
            context['error_msg'] = self.request.session['error_msg']
            return render(self.request, self.template_name, context)

        user = authenticate(self.request, username=ogg.username, password=password)

        if user is None:
            self.request.session['error_msg'] = "Invalid password"
            context['error_msg'] = self.request.session['error_msg']
            return render(self.request, self.template_name, context)

        login(self.request, user)

        self.request.session['error_msg'] = None

        if remember_me:
            self.request.session.set_expiry(None)
        else:
            self.request.session.set_expiry(43200)

        return redirect(self.success_url)


class RegisterUserView(View):
    form_class = RegisterForm
    template_name = 'generatorApp/register.html'
    success_url = reverse_lazy('generatorApp:home')

    def get(self, request):
        return render(self.request, self.template_name)

    def post(self, request):
        context = {}
        username = self.request.POST.get('login')
        password1 = self.request.POST.get('password')
        password2 = self.request.POST.get('rpassword')
        email = self.request.POST.get('email')

        if username in User.objects.values_list('username', flat=True):
            self.request.session['error_msg'] = "This username is already taken."
            return render(self.request, self.template_name, context)

        if email in User.objects.values_list('email', flat=True):
            self.request.session['error_msg'] = "This email is already taken."
            return render(self.request, self.template_name, context)

        if password1 != password2:
            self.request.session['error_msg'] = "Please pass in the same password!"
            return render(self.request, self.template_name, context)

        # Individual regex checks for tailored feedback
        if len(password1) < 8:
            self.request.session['error_msg'] = "Password must be at least 8 characters long."
            return render(self.request, self.template_name, context)

        if not re.search(r'[A-Z]', password1):
            self.request.session['error_msg'] = "Password must contain at least one uppercase letter."
            return render(self.request, self.template_name, context)

        if not re.search(r'[a-z]', password1):
            self.request.session['error_msg'] = "Password must contain at least one lowercase letter."
            return render(self.request, self.template_name, context)

        if not re.search(r'[@$!%*?&]', password1):
            self.request.session['error_msg'] = "Password must contain at least one special character (@, $, !, %, *, ?, &)."
            return render(self.request, self.template_name, context)

        user = User.objects.create_user(username, email, password1)
        user.save()
        auth_user = authenticate(username=username, password=password1)
        login(self.request, auth_user)

        self.request.session['error_msg'] = None

        return redirect(self.success_url)


class LogoutUserView(LoginRequiredMixin, View):
    login_url = reverse_lazy('generatorApp:login')

    def post(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('generatorApp:home'))

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('generatorApp:home'))

scheduleGenerator/generatorApp/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import *
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def login_register(request):
    if request.user.is_authenticated:
        messages.success(request, f'You are logged as {request.user.username}')
        return HttpResponseRedirect(reverse('generatorApp:home'))

    return render(request, 'generatorApp/login_register.html', {})


def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(
            request,
            username=username,
            password=password
        )

        if user is not None:
            login(request, user)
            messages.success(request, f'You are logged as {user.username}')
            return HttpResponseRedirect(reverse('generatorApp:home'))
        else:
            messages.error(request, 'Login failed. Please check your username and password.')
            return HttpResponseRedirect(reverse('generatorApp:login_register'))

    return HttpResponseRedirect(reverse('generatorApp:login_register'))


def register_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        repeat_password = request.POST.get('repeat-password')

        if Users.objects.filter(username=username).exists():
            messages.error(request, 'This username is taken. Please choice different one.')
            return HttpResponseRedirect(reverse('generatorApp:login_register'))

        if password != repeat_password:
            messages.error(request, 'Passwords must be identical!')
            return HttpResponseRedirect(reverse('generatorApp:login_register'))

        user = Users(
            username=username,
            password=password
        )
        user.save()

        login(request, user)

        messages.success(request, f'You are logged as {user.username}')
        return HttpResponseRedirect(reverse('generatorApp:home'))

    return HttpResponseRedirect(reverse('generatorApp:login_register'))


def home(request):
    return render(request, 'generatorApp/home.html')

generatorApp/templates/generatorApp/home.html
{% extends 'generatorApp/index.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'generatorApp/home.css' %}">
    <title>home</title>
{% endblock %}

{% block content %}

    <div class="home">
        <h1>School Schedule Generator</h1>
    </div>

{% endblock %}

generatorApp/templates/generatorApp/index.html
<!--jesli ta linijka bedzie powodowala blad przeniesz ja pod doctype, nie wiem czemu w pycharm podokresla-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'generatorApp/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap"
    rel="stylesheet">
    {% block head %}
        <title>SSG</title>
    {% endblock %}
</head>
<body>
    <div class="nav nav-top">
        <a href="{% url 'generatorApp:home' %}" id="logo">SSG</a>
        <ul>
            {% if user.is_authenticated %}
                <li>
                    <a id="logout" class="menu-item">
                        Logout
                    </a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'generatorApp:register' %}">
                        <div class="btn">Sign up</div>
                    </a>
                </li>
                <li>
                    <a class="menu-item" href="{% url 'generatorApp:login' %}">
                         Sign in
                    </a>
                </li>

            {% endif %}

            <div class="spacer"></div>

            <li>
                <a class="menu-item" href="{% url 'generatorApp:docs' lang='eng' file='intro' %}">Documentation</a>
            </li>

            <li>
                <a class="menu-item" {% if user.is_authenticated %} href="{% url 'generatorApp:schedules' username=user.username %}"
                {% else %} href="{% url 'generatorApp:login' %}" {% endif %}>Schedules</a>
            </li>
        </ul>
    </div>

    <div id="msg-container" class="sticky-wrapper">
        {% if warning_msg or request.session.warning_msg %}
            <p class="msg" style="background-color: #e8d873; color: #a48509;">
                {{ request.session.warning_msg|safe }}
                <span class="close-btn" onclick="closeMessage(this, 'warning_msg')">&times;</span>
            </p>
        {% endif %}
        {% if error_msg or request.session.error_msg %}
            <p class="msg" style="background-color: #e87373; color: #a90f0f;">
                {{ request.session.error_msg|safe }}
                <span class="close-btn" onclick="closeMessage(this, 'error_msg')">&times;</span>
            </p>
        {% endif %}
    </div>

    <div id="popup" class="overlay">
        <form id="popup-form" method="GET">
            {% csrf_token %}
            <h2 id="popup-msg"></h2>
            <div>
                <a id="popup-confirm" href="">yes</a>
                <a href="">no</a>
            </div>
        </form>
    </div>

    <div id="empty-overlay" class="overlay"></div>


    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

    <footer>
        <div>&copy 2024</div>
        <a class="menu-item" href="">donate us 🙏</a>
        <a class="menu-item" href="https://github.com/School-Schedule-Generator/School.Schedule.Generator" target="_blank">github</a>
    </footer>

    <div class="lds-ellipsis" id="loader"><div></div><div></div><div></div><div></div></div>

    {% block js %}
    {% endblock %}

    <script src="{% static 'generatorApp/script.js' %}"></script>
    <script src="{% static 'generatorApp/file_input.js' %}"></script>
    <script>
        const logout = document.getElementById("logout");
        const popup = document.getElementById("popup");
        const popup_msg = document.getElementById('popup-msg')
        const popup_confirm = document.getElementById('popup-confirm')
        const empty_overlay = document.getElementById('empty-overlay')
        empty_overlay.style.display = "none"

        logout.addEventListener('click', () => {
            popup.style.display = "flex"
            popup_msg.innerHTML = "logout?";
            popup_confirm.href = "{% url 'generatorApp:logout' %}"
        })

        popup.addEventListener('click', () => {
            popup.style.display = "none"
        })

        function show_loader() {
            document.getElementById("loader").style.display = "inline-block";
            empty_overlay.style.display = "flex"
        }

        function closeMessage(element, msgType) {
            element.parentElement.style.display = 'none';
            // Create an AJAX request to remove the message from the session
            fetch('/remove-message/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}' // Make sure you pass the CSRF token for security
                },
                body: JSON.stringify({ msg_type: msgType })
            }).then(response => {
                if (!response.ok) {
                    console.error('Failed to remove the message from session.');
                }
            }).catch(error => {
                console.error('Error:', error);
            });
        }
    </script>

</body>
</html>

generatorApp/templates/generatorApp/schedule.html
{% extends 'generatorApp/index.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'generatorApp/schedule.css' %}">
    <title>schedules</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}

{% block content %}

   {% include 'generatorApp/schedule_list.html' %}

    <main class="main">

        <div class="schedule-info">
            <h3 id="title">{{ schedule.name }}</h3>
            <div class="button-container">
                <a class="confirm-button schedule-btn-center" id="delete_btn">Delete</a>
                <a class="schedule-btn-center" href="{% url 'generatorApp:export_schedule' username=user.username schedule_name=schedule.name %}">Export</a>
                <a class="schedule-btn-center" href="{% url 'generatorApp:settings' username=user.username schedule_name=schedule.name %}">Settings</a>
                <a class="schedule-btn-center" href="{% url 'generatorApp:generate_schedule' username=user.username schedule_name=schedule.name %}" onclick="show_loader()">Generate</a>
            </div>
            <a class="schedule-info-btn">{{ schedule.description }}</a>
            <div id="class-buttons" class="button-container">
                {% for class in classes %}
                    <div class="class-switch schedule-btn-center" onclick="switch_class({{ class.in_id }})">
                        {{ class.grade }}{{ class.class_signature }}
                    </div>
                {% endfor %}
            </div>
        </div>

        <br>

        {% if schedule_content.items %}
        <div class="schedules" id="schedules">
            {% for class_id, days in schedule_content.items %}
                <div id="{{ class_id }}" class="schedule" style="display: none">
                    <h3 style="float: left; padding-right: 1ch;">
                        {% for class_name in schedule.classes_set.all%}
                            {% if class_name == class_id %}
                                <div>{{ class_name }}</div>
                            {% endif %}
                        {% endfor %}
                    </h3>
                    <div class="days">
                        {%  for day, subjects in days.items %}
                            <div class="day">
                                <h3> {{ day }}</h3>
                                <div class="subjects">
                                    {% for subject_list in subjects %}
                                        <div class="groups">
                                            {% for subject in subject_list %}
                                                <div class="subject">
                                                    <div>Time: <span class="data">{{ subject.lesson_hour_id }}</span></div>
                                                    <div>Subject: <span class="data">{{ subject.subject_name_id }}</span></div>
                                                    <div>Teacher: <span class="data">{{ subject.teachers_id }}</span></div>
                                                    <div>Class: <span class="data">{{ subject.classroom_id }}</span></div>
                                                    <div>Group: <span class="data">{{ subject.group }}</span></div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div style="clear: both"></div>
    {% else %}
            <div id="center-msg">
                <div></div>
                <div id="no-schedule-msg">Generate Schedule</div>
                <div></div>
            </div>
    {% endif %}

    </main>
{% endblock %}

{% block js %}
    <script>
        // Function to switch the visible class schedule
        function switch_class(class_id) {
            // Hide all class schedules
            document.querySelectorAll('.schedule').forEach(schedule => {
                schedule.style.display = 'none';
            });

            // Show the selected class schedule
            document.getElementById(class_id).style.display = 'block';
        }

        // Set the first class to be visible on page load
        window.onload = function() {
            // Find the first class schedule div and make it visible
            const firstClass = document.querySelector('.schedule');
            if (firstClass) {
                firstClass.style.display = 'block';
            }

            // Optionally, highlight the first button
            const firstButton = document.querySelector('.class-switch');
            if (firstButton) {
                firstButton.classList.add('active');  // Add active class for visual feedback (e.g., highlight)
            }
        };

        // Add click event listeners to switch buttons
        document.querySelectorAll('.class-switch').forEach(button => {
            button.addEventListener('click', () => {
                // Remove 'active' class from all buttons
                document.querySelectorAll('.class-switch').forEach(btn => {
                    btn.classList.remove('active');
                });

                // Add 'active' class to the clicked button
                button.classList.add('active');

                // Call the function to switch class schedules
                switch_class(button.getAttribute('onclick').match(/\d+/)[0]);
            });
        });

        let delete_btn = document.getElementById("delete_btn");

        delete_btn.addEventListener('click', () => {
            popup.style.display = "flex"
            popup_msg.innerHTML = "delete?";
            popup_confirm.href = "{{ request.get_full_path }}" + "delete"
        })
    </script>
{% endblock %}

generatorApp/templates/generatorApp/schedule_list.html
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'generatorApp/aside.css' %}">
{% endblock %}

<aside class="sticky-wrapper">
    <div class="aside-content">
        <h3>
            <span>List of your schedules</span>
            <a href="{% url 'generatorApp:schedules_base' %}">
                <span style="font-size: 150%">+</span>
            </a>
        </h3>

        <ol class="scrollable">
            {% if schedule_list %}
                {% for schedule in schedule_list %}
                    <li>
                        <a href="{% url 'generatorApp:schedule' username=user.username schedule_name=schedule.name %}">
                            {{ schedule.name }}, {{ schedule.created_date }}
                        </a>

                        <ul class="schedule-data-list" style="padding-left: 2ch">
                            {% for label in labels %}
                                <li><a href="{% url 'generatorApp:schedule' username=user.username schedule_name=schedule.name%}{{label}}">{{ label }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            {% else %}
                <p>It seems to you don't have any schedules :<</p>
            {% endif %}
        </ol>

        
        <form method="GET" id="sort-form">
            <h4>Sort by:</h4>
            <select name="sort_by" id="sort_by">
                <option value="name">Name(A-Z)</option>
                <option value="created_date">Created date</option>
            </select>
        </form>
    </div>

    <button id="toggleAside" class="toggle-btn">
        <span id="arrow">←</span>
    </button>
</aside>

{% block js %}
    <script>
        $(document).ready(()=>{
            $('#sort_by').change(()=>{
                $('#sort-form').submit()
            })
        })

        const urlParams = new URLSearchParams(window.location.search)
        const sortBy = urlParams.get('sort_by')
        if(sortBy){
            $('#sort_by').val(sortBy)
        }

        document.getElementById('toggleAside').addEventListener('click', function() {
            const aside = document.querySelector('aside');
            const main = document.querySelector('main')
            const arrow = document.getElementById('arrow');

            if (aside.classList.contains('aside-hidden')) {
                aside.classList.remove('aside-hidden');
                main.classList.remove('main-fill');
                arrow.textContent = '←'; // Point the arrow left
            } else {
                aside.classList.add('aside-hidden');
                main.classList.add('main-fill');
                arrow.textContent = '→'; // Point the arrow right
            }
        });
    </script>
{% endblock %}